spring.datasource.url=jdbc:postgresql://localhost:5432/S18D3_hospital_db
spring.datasource.username=postgres
spring.datasource.password=hi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect